version: '3.8'

services:
  bot:
    build: 
      context: .
      args:
        - USER_ID=${USER_ID:-1000}
        - GROUP_ID=${GROUP_ID:-1000}
    image: ${SYSTEM_NAME}
    container_name: ${SYSTEM_NAME}
    restart: on-failure:5
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 5
    env_file:
      - .env
    volumes:
      - ./data:/app/data:rw
      - logs:/app/logs:rw
    environment:
      - TZ=Asia/Novosibirsk
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD", "/app/scripts/healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  test:
    build:
      context: .
      args:
        - USER_ID=${USER_ID:-1000}
        - GROUP_ID=${GROUP_ID:-1000}
    image: ${SYSTEM_NAME}-test
    container_name: ${SYSTEM_NAME}-test
    env_file:
      - .env
    volumes:
      - ./data:/app/data:rw
      - logs:/app/logs:rw
    environment:
      - TZ=Asia/Novosibirsk
      - PYTHONUNBUFFERED=1
    command: python -m tests.integration.test_notifications --token "$BOT_TOKEN"
    entrypoint: []

# Named volumes for data persistence
volumes:
  logs:
    driver: local
