version: '3.8'

services:
  bot:
    build:
      context: .
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
    image: ${SYSTEM_NAME:-telegram-bot}:latest
    container_name: ${SYSTEM_NAME:-telegram-bot}
    restart: unless-stopped
    
    # Resource limits for stability
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
        reservations:
          memory: 128M
          cpus: '0.25'
    
    # Environment configuration
    env_file:
      - .env
    environment:
      - TZ=${TZ:-UTC}
      - PYTHONPATH=/app
    
    # Data persistence
    volumes:
      - ./data:/app/data:rw
      - ./logs:/app/logs:rw
    
    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        compress: "true"
    
    # Health monitoring
    healthcheck:
      test: ["CMD", "pgrep", "-f", "python.*src.bot"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    
    # Network isolation
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge
    name: ${SYSTEM_NAME:-telegram-bot}-network
