version: '3.8'

services:
  bot:
    build:
      context: .
      args:
        - USER_ID=${USER_ID:-1000}
        - GROUP_ID=${GROUP_ID:-1000}
        - BUILD_ID=${BUILD_ID:-latest}
    image: ${SYSTEM_NAME:-quit-smoking-bot}:latest
    container_name: ${SYSTEM_NAME:-quit-smoking-bot}
    
    restart: unless-stopped
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
        reservations:
          memory: 128M
          cpus: '0.25'
    
    env_file:
      - .env
    environment:
      - TZ=Asia/Novosibirsk
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app/src
      - IN_CONTAINER=true
    
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
        compress: "true"
        labels: "service=quit-smoking-bot"
    
    healthcheck:
      test: ["CMD", "/app/scripts/health.sh", "--mode", "docker"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    
    volumes:
      - ./data:/app/data:rw
      - ./logs:/app/logs:rw
    
    networks:
      - bot-network
    
    security_opt:
      - no-new-privileges:true
    read_only: false
    tmpfs:
      - /tmp:noexec,nosuid,size=100m

  health-monitor:
    image: ${SYSTEM_NAME:-quit-smoking-bot}:latest
    container_name: ${SYSTEM_NAME:-quit-smoking-bot}-health-monitor
    restart: unless-stopped
    profiles: ["monitoring"]
    
    depends_on:
      bot:
        condition: service_healthy
    
    environment:
      - TZ=Asia/Novosibirsk
      - PYTHONUNBUFFERED=1
      - MONITORING_MODE=true
      - SYSTEM_NAME=${SYSTEM_NAME:-quit-smoking-bot}
    
    volumes:
      - ./logs:/app/logs:rw
      - ./data:/app/data:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    
    entrypoint: ["/bin/bash"]
    command: ["/app/scripts/health-monitor.sh"]
    
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "3"
        labels: "service=health-monitor"
    
    networks:
      - bot-network
    
    user: root



  log-aggregator:
    image: alpine:latest
    container_name: ${SYSTEM_NAME:-quit-smoking-bot}-log-aggregator
    restart: unless-stopped
    profiles: ["logging"]
    
    volumes:
      - ./logs:/logs:rw
    
    command: >
      sh -c "
        while true; do
          find /logs -name '*.log' -type f -size +50M -exec sh -c 'mv \"$$1\" \"$$1.old\" && touch \"$$1\"' _ {} \;
          find /logs -name '*.log.old' -mtime +7 -delete
          sleep 3600
        done
      "
    
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"

networks:
  bot-network:
    driver: bridge
    name: ${SYSTEM_NAME:-quit-smoking-bot}-network
