version: '3.8'

services:
  bot:
    build:
      context: .
      args:
        - USER_ID=${USER_ID:-1000}
        - GROUP_ID=${GROUP_ID:-1000}
        - BUILD_ID=${BUILD_ID:-latest}
    image: ${SYSTEM_NAME:-quit-smoking-bot}:latest
    container_name: ${SYSTEM_NAME:-quit-smoking-bot}
    
    restart: unless-stopped
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
        reservations:
          memory: 128M
          cpus: '0.25'
    
    env_file:
      - .env
    environment:
      - TZ=${TZ:-UTC}
      - PYTHONPATH=/app/src
    
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
        compress: "true"
        labels: "service=quit-smoking-bot"
    
    healthcheck:
      test: ["CMD", "sh", "-c", "pgrep -f 'python.*src' > /dev/null"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    
    volumes:
      - ./data:/app/data:rw
      - ./logs:/app/logs:rw
    
    networks:
      - bot-network
    
    security_opt:
      - no-new-privileges:true
    read_only: false
    tmpfs:
      - /tmp:noexec,nosuid,size=100m

  monitor:
    build:
      context: .
      dockerfile: Dockerfile.monitor
    image: ${SYSTEM_NAME:-quit-smoking-bot}-monitor:latest
    container_name: ${SYSTEM_NAME:-quit-smoking-bot}-monitor
    restart: unless-stopped
    profiles: ["monitoring"]
    
    depends_on:
      bot:
        condition: service_healthy
    
    environment:
      - TZ=${TZ:-UTC}
      - SYSTEM_NAME=${SYSTEM_NAME:-quit-smoking-bot}
    
    volumes:
      - ./logs:/logs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    
    command: >
      sh -c "
        while true; do
          echo \"\$(date): Checking bot health...\" >> /logs/monitor.log
          if docker ps --filter name=\${SYSTEM_NAME} --filter status=running -q | grep -q .; then
            echo \"\$(date): Bot container is running\" >> /logs/monitor.log
          else
            echo \"\$(date): WARNING - Bot container not running!\" >> /logs/monitor.log
          fi
          sleep 60
        done
      "
    
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "3"
        labels: "service=monitor"
    
    networks:
      - bot-network

  log-aggregator:
    image: alpine:latest
    container_name: ${SYSTEM_NAME:-quit-smoking-bot}-log-aggregator
    restart: unless-stopped
    profiles: ["logging"]
    
    volumes:
      - ./logs:/logs:rw
    
    command: >
      sh -c "
        while true; do
          find /logs -name '*.log' -type f -size +50M -exec sh -c 'mv \"$$1\" \"$$1.old\" && touch \"$$1\"' _ {} \;
          find /logs -name '*.log.old' -mtime +7 -delete
          sleep 3600
        done
      "
    
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"

networks:
  bot-network:
    driver: bridge
    name: ${SYSTEM_NAME:-quit-smoking-bot}-network
