# Production overrides for docker-compose.yml
version: '3.8'

services:
  bot:
    # Production-specific configurations
    restart: always
    
    # Production environment
    environment:
      - LOG_LEVEL=INFO
      - PRODUCTION=true
      - PYTHONPATH=/app
    
    # Stricter resource limits for production
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
        reservations:
          memory: 128M
          cpus: '0.25'
    
    # Production healthcheck (standard intervals)
    healthcheck:
      test: ["CMD", "pgrep", "-f", "python.*src.bot"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    
    # Production logging (more conservative)
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "5"
        compress: "true"
    
    # Security and stability
    security_opt:
      - no-new-privileges:true
    
    # Production volumes (read-only code)
    volumes:
      - ../data:/app/data:rw
      - ../logs:/app/logs:rw
      # Code is baked into image, no live mounting
    
    # Production labels for monitoring
    labels:
      - "com.example.service=quit-smoking-bot"
      - "com.example.environment=production"
      - "com.example.monitoring=enabled"