version: '3.8'

# Project name for Docker Desktop grouping
name: ${SYSTEM_NAME:-quit-smoking-bot}

services:
  bot:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
    image: ${SYSTEM_NAME:-quit-smoking-bot}:latest
    container_name: ${SYSTEM_NAME:-quit-smoking-bot}
    restart: always
    
    # Production resource limits for stability
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
        reservations:
          memory: 128M
          cpus: '0.25'
    
    # Environment configuration
    env_file:
      - ../.env
    environment:
      - TZ=${TZ:-UTC}
      - PYTHONPATH=/app
      - LOG_LEVEL=INFO
      - PRODUCTION=true
    
    # Data persistence
    volumes:
      - ../data:/app/data:rw
      - ../logs:/app/logs:rw
    
    # Production logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "5"
        compress: "true"
    
    # Health monitoring
    healthcheck:
      test: ["CMD", "pgrep", "-f", "python.*src.bot"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    
    # Security and stability
    security_opt:
      - no-new-privileges:true
    
    # Production labels for monitoring
    labels:
      - "com.example.service=quit-smoking-bot"
      - "com.example.environment=production"
      - "com.example.monitoring=enabled"
    
    # Network isolation
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge
    name: ${SYSTEM_NAME:-quit-smoking-bot}-network
